### PR TITLE
Ray-by-ray filtering + Examples

### PR DESCRIPTION
**Pull request by salah-saleh**
The Ray-by-ay filtered back projection is an algorithm that aim at reducing the noise effect in the cases of noisy FBP data. Traditionally, only a highpass filter is used e.g. ramp filter. Hence, the noise remains unaffected in the reconstructed images. The Ray-by-ray algorithm suggests modeling the projection noise on a ray-by-ray basis. The idea is to construct a set of lowpass filters of different strengths and to combine them with the traditional highpass filter. Depending on the noise variance of the ray measured, a weight is assigned. In 'CONRAD/src/edu/stanford/rsl/conrad/filtering/RayByRayFiltering.java', we implemented the algorithm based on Zeng's paper 'A filtered backprojection algorithm with ray-by-ray noise weighting'. In his paper, Zeng suggested implementing 11 frequency domain filter. Based on the noise variance of the ray, only one of those filters is applied to the ray before its final reconstruction. The 11 filters are a combination of different lowpass filters and the traditional ramp filter. There are many parameters that can affect the lowpass filters' strengths, and as stated by the author, the interaction between them is not entirely clear. However, one of the author suggestions is to set the parameter 'K' to 0 and and the parameter 'beta' to a very low number (in the order of E-4). Increasing 'beta' will then increase the effect of the smoothing and visa versa. For more demonstration and testing on the effect of those parameters, the reader is encourage to check the examples implemented in the following files:    
CONRAD/src/edu/stanford/rsl/tutorial/fan/RbRFanBeamReconstructionExample.java
CONRAD/src/edu/stanford/rsl/tutorial/RayByRayFilterExample.java
The following image demonstrate the difference between the traditional ramp filter and the Ray-by-ray filter
screen shot 2015-02-23 at 08 58 33
screen shot 2015-02-23 at 09 00 05

### CODE REVIEW

**Comment by akmaier** [comment]
Can you please remove all the binary files from your fork and resend this pull request?

**Comment by salah-saleh** [comment]
Ok I fixed the issue. Now you can pull only the files that I have changed. I removed the unnecessary files.

**Comment by akmaier** [comment]
Can you also refactor src/edu/stanford/rsl/conrad/filtering/RayByRayFiltering.java to src/edu/stanford/rsl/tutorial/RayByRayFiltering.java ?
It might make sense to create a new package in tutorial where all the filters can be stored...

**Comment by akmaier** [comment]
And I just realized that the ellipsoid Phantom and the ray-by-ray filtering are missing correct Copyright notes. You Need to add your Name in ellipsoid Phantom and the Copyright note in the ray-by-ray filtering.

Best,

Andreas

**Comment by salah-saleh** [comment]
I updated to cover your comments. Please check now.

**Comment by akmaier** [comment]
Changes look good. However, I disagree with the changes in src/edu/stanford/rsl/conrad/phantom/EllipsoidPhantom.java. Can you revert them?
Best,

Andreas

**Comment by salah-saleh** [comment]
It was a mistake to push this file. I had my ellipsoid implementation in the tutorial/phantoms/Ellipsoid.java file. I removed the phantom/EllipsoidPhantom.java file from my pull request.

**Pull request merged**
