### PR TITLE
Add Travis CI to CONRAD

### PR DESCRIPTION
**Pull request by theHamsta**
Travis is an automatic continuous integration tool. Every time a commit is pushed to the upstream repository or a pull request is created the repository is automatically built on various virtual machines. This can help to detect errors on other operating systems (Travis supports Linux and OSX) or Java versions. Also tests can be run automatically on each commit and JAR files. We can use Travis for free since we are a public github repo.

Currently, CONRAD builds fine on JDK8 and openjdk8, but there seems to be a small problem with JDK9:
https://travis-ci.org/theHamsta/CONRAD
Additionally, there is also a problem with OpenCL on Linux machines when running CONRAD from the JAR file.

I added the necessary configuration file .travis.yml and a ant build file since Travis needs a possibility to build CONRAD from command line. I am not sure if this is what we want.

### CODE REVIEW

**Comment by akmaier** [comment]
What do the changes in GridComplex and Attract, etc. have in common with Travis CI?

**Comment by theHamsta** [comment]
The files have in common that they weren't encoded using utf8 but some Windows encoding. So the build system refused to compile whenever there was a German umlaut ÄÖÜ. 

Ant build isn't a very sophisticated build system but could be directly exported by eclipse. Maybe another build system can directly Eclipse's .classpath files. I think you can even use Eclipse from command line: https://stackoverflow.com/questions/206473/build-eclipse-java-project-from-command-line.

I don't know whether this PR is still relevant. It was created over a year ago when I started at the lab.

**Comment by akmaier** [comment]
Why do we need a continuous integration system? We are platform independent and testing can be performed in JUnit...

**Comment by theHamsta** [comment]
Travis can perform JUnit tests automatically (thats what it's made for). Maintainers could see if a PR breaks one of the tests since most user of CONRAD run the test manually.

Different Java version have different features and CONRAD uses native extensions (e.g. for OpenCL, some file formats)... Would we notice if some user submits a Java 11 feature in some rarely used file and know that Java 8 is not supported in all CONRAD files anymore?

**Comment by theHamsta** [comment]
But as I said, most lab members considered CI an overkill. So the issue can be closed.

**Pull request closed without merging**
