### PR TITLE
Project Iris Kellermann

### PR DESCRIPTION
**Pull request by pelma24**
Finished the creation of a channelized hotelling observer using Laguerre Gauss channels.

### CODE REVIEW

**Comment by akmaier** [comment]
I do not think that the package name is consistent with the rest of the repository. Shouldn't we relocate this somewhere into the tutorial package?

**Comment by pelma24** [comment]
Yes, that's right. I wasn't sure if I'm allowed to put the files somewhere else because we were originally told to create a new package for our projects. Should I move the files to the tutorial package?

**Comment by akmaier** [comment]
Yes please. Create an appropriate package there.

**Comment by bergerma** [comment]
Dear Iris,
this is a reminder to move your code to the tutorial package as communicated above.
Thanks
Martin

**Comment by pelma24** [comment]
I'm sorry that it took so long but the package is now moved to the tutorial.

**Pull request merged**
