### PR TITLE
EpipolarConsistency

### PR DESCRIPTION
**Pull request by mapcreater**
class to allow for comparison of different views by the Epipolar
Consistency Conditions

### CODE REVIEW

**Comment by akmaier** [comment]
Shouldn't "PlueckerMatrixDual", etc, go to the Math Library? I think the best option would be to put these methods to "SimpleOperators". Could you also think of a name that does not start with a capital letter?
Can you create your examples synthetically? At present you require files on the hard disk. This would mean that you have to add these files to the repository. I'd rather generate the data using the ConeBeamExample...

**Comment by mapcreater** [comment]
I have moved the mathematical implementations to SimpleOperators.java.
But I don't really understand the second part. For my example it is neccessery to load files from the disk. I use a data set of a pumpkin with two different views. I think it will not be a good idea to simulate a sinogram instead, as it is done in ConebeamExample. Always when we simulated something in the CT reconstruction course we made also use of files from the hard disk (knee data set). So how could I cope without the hard disk files?

**Comment by akmaier** [comment]
Can we simulate a Cone-Beam Scan, then modify the projection matrices and run the consistency metric? in this way, we would generate the data on-the-fly and do not have to ship it with CONRAD. And of course the example is more intuitive...

**Comment by mapcreater** [comment]
I have done further changes in the interface of class and method. At the moment I failed to push and commit. I will try again on Monday on the other PC.

**Comment by bergerma** [comment]
Hi mapcreater,

can you please do a new synchronization with the current base of CONRAD and resolve the conflict in the SimpleOperators class? Thanks.

Please also do the following:
1) Remove the copyright notices at your method in the SimpleOperators file. One copyright notice at the top or bottom of the file is sufficient and you already added your name to the authorlist of the file.
2) Please move the method "computeRadonTrafoAndDerive" from the SimpleOperators class to your own EpipolarConsistency class file as it does not have anything to do with matrices.

Afterwards we should be good for merging your code into the repository.

Thanks
Martin

**Pull request merged**
